namespace WebApplication_API.Services;

internal static class LocationQrThemeCatalog
{
    public static IReadOnlyList<LocationQrThemeDefinition> Themes { get; } =
    [
        new(
            "hotpot",
            "Hotpot",
            "🍲",
            "#d94430",
            "#8b3923",
            "#ff8a5b",
            "#fde2da",
            "#fff7f4",
            "#ffffff",
            "#1e140f",
            "#7c4f45",
            "#fde2da",
            "#8b3923",
            false,
            "Warm fire tones for hot pot restaurants."),
        new(
            "snail",
            "Snail Stalls",
            "🐌",
            "#2d5016",
            "#1a3d0a",
            "#6fbf52",
            "#dff3d7",
            "#f5fbf1",
            "#ffffff",
            "#11210b",
            "#4d6942",
            "#dff3d7",
            "#1a3d0a",
            false,
            "Coastal and street-market tones for snail vendors."),
        new(
            "pub",
            "Pubs/Beer",
            "🍺",
            "#3d2817",
            "#1a1410",
            "#facc15",
            "#fef08a",
            "#0f0c0a",
            "#1a1410",
            "#f8f3ee",
            "#d5bca6",
            "#facc15",
            "#2f1a08",
            true,
            "Dark night and neon tones for pubs and beer halls."),
        new(
            "dessert",
            "Bubble Tea/Desserts",
            "🧋",
            "#f596aa",
            "#d95e8a",
            "#6ee7b7",
            "#d7fae9",
            "#fff7fb",
            "#ffffff",
            "#3e1027",
            "#8f5b75",
            "#d7fae9",
            "#8f2452",
            false,
            "Pastel pink tones for bubble tea and dessert shops."),
        new(
            "fastfood",
            "Fast Food",
            "🍔",
            "#ff6b35",
            "#ff4500",
            "#ffd166",
            "#fff0d8",
            "#fff8f3",
            "#ffffff",
            "#311108",
            "#8a4a35",
            "#fff0d8",
            "#9a3b10",
            false,
            "Bright orange pop-art tones for fast food spots."),
        new(
            "junkfood",
            "Junk Food Vendor",
            "🌭",
            "#ffd700",
            "#caa400",
            "#ff6b35",
            "#ffeeb1",
            "#121212",
            "#181818",
            "#fffbe6",
            "#d9c768",
            "#ffed4e",
            "#332600",
            true,
            "Electric street gold for bold late-night snacks."),
        new(
            "dinner",
            "Vendor Dinner Food",
            "🍲",
            "#8b4513",
            "#5c2d0b",
            "#fcd34d",
            "#ffefb8",
            "#17100b",
            "#24150c",
            "#fff7ed",
            "#d2b9a4",
            "#fcd34d",
            "#4a2c00",
            true,
            "Candlelight evening browns for dinner stalls."),
        new(
            "coffee",
            "Coffee Shop",
            "☕",
            "#6f4e37",
            "#3e2723",
            "#d4a35a",
            "#f1e0c5",
            "#fbf6f1",
            "#ffffff",
            "#23160f",
            "#7d5d49",
            "#f1e0c5",
            "#5f3d23",
            false,
            "Espresso artisan browns for coffee houses."),
        new(
            "smoothie",
            "Smoothie Takeaway",
            "🥤",
            "#ff69b4",
            "#ff1493",
            "#34d399",
            "#d1fae5",
            "#fff7fb",
            "#ffffff",
            "#3b0827",
            "#8a4570",
            "#d1fae5",
            "#0f6d54",
            false,
            "Tropical burst pink for smoothie takeaway counters."),
        new(
            "buffet",
            "Buffet Restaurant",
            "🍽️",
            "#ffd700",
            "#ffa500",
            "#b45309",
            "#fff0b3",
            "#fffaf0",
            "#ffffff",
            "#2d1b00",
            "#826236",
            "#fff0b3",
            "#7c4a03",
            false,
            "Grand feast gold for buffet dining rooms."),
        new(
            "foodcourt",
            "Food Court",
            "🏪",
            "#4a7c59",
            "#2d5a3d",
            "#fb923c",
            "#ffe1c7",
            "#f4faf6",
            "#ffffff",
            "#102318",
            "#50705d",
            "#d8f0df",
            "#274631",
            false,
            "Urban hub green for market-style food courts."),
        new(
            "canteen",
            "Canteen",
            "🍱",
            "#87ceeb",
            "#4da6d6",
            "#0ea5e9",
            "#d9f2ff",
            "#f5fbff",
            "#ffffff",
            "#0d2430",
            "#4c7286",
            "#d9f2ff",
            "#176186",
            false,
            "Clean functional sky blue for canteens."),
        new(
            "supermarket",
            "Supermarket",
            "🛒",
            "#0066cc",
            "#0052a3",
            "#22c55e",
            "#d7f7e3",
            "#f4f9ff",
            "#ffffff",
            "#0b1b33",
            "#4b6d93",
            "#d7f7e3",
            "#0a5a34",
            false,
            "Fresh retail blue for supermarkets."),
        new(
            "minimart",
            "Mini Mart",
            "🏬",
            "#ff6b9d",
            "#ff4757",
            "#84cc16",
            "#ecfccb",
            "#fff6f9",
            "#ffffff",
            "#36111d",
            "#91566d",
            "#ecfccb",
            "#3f6212",
            false,
            "Corner-store warmth with lively pink highlights."),
        new(
            "bakery",
            "Bakery",
            "🍰",
            "#f4a261",
            "#e76f51",
            "#eab308",
            "#fff1c4",
            "#fffaf4",
            "#ffffff",
            "#31170b",
            "#93664d",
            "#fff1c4",
            "#8a5a0b",
            false,
            "Golden crust oranges for bakeries."),
        new(
            "eatery",
            "Eatery / Rice Shop",
            "🍚",
            "#daa520",
            "#cd853f",
            "#84cc16",
            "#ecfccb",
            "#fffaf0",
            "#ffffff",
            "#2c1f0c",
            "#866d47",
            "#fff0c6",
            "#5a4b11",
            false,
            "Homestyle golden tones for rice shops and eateries."),
        new(
            "seafood",
            "Seafood Restaurant",
            "🦐",
            "#20b2aa",
            "#0e7490",
            "#fb923c",
            "#ffe3cf",
            "#f0fcfd",
            "#ffffff",
            "#0b2630",
            "#4f7982",
            "#d4f7f5",
            "#0d5b66",
            false,
            "Ocean teal for seafood restaurants."),
        new(
            "noodle",
            "Noodle Shop",
            "🍜",
            "#c1440e",
            "#8b2e0b",
            "#fbbf24",
            "#ffefb7",
            "#fff8f3",
            "#ffffff",
            "#2c1108",
            "#84543f",
            "#ffefb7",
            "#7a3e0c",
            false,
            "Steamy umami reds for noodle shops."),
        new(
            "pho",
            "Pho Shop",
            "🍲",
            "#a0522d",
            "#704214",
            "#f59e0b",
            "#ffe5ba",
            "#fdf7f2",
            "#ffffff",
            "#24140d",
            "#7c604d",
            "#ffe5ba",
            "#6d3f12",
            false,
            "Vietnamese heritage sienna for pho shops."),
        new(
            "stickyrice",
            "Sticky Rice Stall",
            "🌾",
            "#ffa500",
            "#ff8c00",
            "#7c3aed",
            "#ede9fe",
            "#fff9ef",
            "#ffffff",
            "#2a1700",
            "#845f34",
            "#ede9fe",
            "#5125a4",
            false,
            "Dawn market orange for sticky-rice stalls."),
        new(
            "cafeteria",
            "Cafeteria",
            "🥗",
            "#90ee90",
            "#3cb371",
            "#f59e0b",
            "#fff0c2",
            "#f5fff6",
            "#ffffff",
            "#0e2512",
            "#54745d",
            "#e2ffe4",
            "#5b3e06",
            false,
            "Mint industrial green for cafeterias.")
    ];

    private static readonly IReadOnlyDictionary<string, LocationQrThemeDefinition> Lookup =
        Themes.ToDictionary(item => item.ThemeName, StringComparer.OrdinalIgnoreCase);

    public static LocationQrThemeDefinition Resolve(string? themeName)
    {
        if (!string.IsNullOrWhiteSpace(themeName)
            && Lookup.TryGetValue(themeName.Trim(), out var definition))
        {
            return definition;
        }

        return Lookup["hotpot"];
    }

    public static string NormalizeThemeName(string? themeName) =>
        Resolve(themeName).ThemeName;
}

internal sealed record LocationQrThemeDefinition(
    string ThemeName,
    string DisplayName,
    string Emoji,
    string PrimaryColor,
    string SecondaryColor,
    string AccentColor,
    string AccentSoftColor,
    string BackgroundColor,
    string CardColor,
    string TextColor,
    string MutedTextColor,
    string BadgeBackgroundColor,
    string BadgeTextColor,
    bool IsDark,
    string Description);
